image: golang:1.9
pipelines:
  default:
    - step:
        script:
          - go version
          - apk update && apk add git
          - go get github.com/golang/dep/cmd/dep
          - mkdir -p "$GOPATH/src/mellium.im/"
          - ln -s "`pwd`" "$GOPATH/src/mellium.im/xmlstream"
          - cd "$GOPATH/src/mellium.im/xmlstream"
          - dep ensure
          - go vet ./...
          - go test -cover ./...
          - go build
