image: golang:1.11beta2-alpine
pipelines:
  default:
    - step:
        script:
          - apk update && apk add gcc libc-dev
          - go version
          - go vet ./...
          - go test -race ./...
          - go test -cover ./...
