image: golang:1.11rc1-alpine
pipelines:
  default:
    - step:
        script:
          - apk update && apk add git gcc libc-dev
          - go version
          - go vet ./...
          - go test -cover ./...
