pipeline:
  info: &info
    image: golang:${GO_VERSION}-alpine
    environment:
      GO111MODULE: "on"
      CGO_ENABLED: "0"
    commands:
      - go version
      - go env
      - go install golang.org/x/lint/golint@latest
      - go install github.com/securego/gosec/cmd/gosec@latest
      - go install git.sr.ht/~samwhited/checkdoc@latest
  test:
    << : *info
    commands: go test -v ./...

matrix:
  GO_VERSION:
    - 1.18
    - 1.17

depends_on:
  - dco
